//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIBike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bikes
    {
        public int BikeID { get; set; }
        public string BikeRef { get; set; }
        public string BikeBrand { get; set; }
        public string BikeModel { get; set; }
        public string BikeColor { get; set; }
        public string BikeType { get; set; }
        public Nullable<int> BikeRating { get; set; }
        public Nullable<decimal> BikePrice { get; set; }
        public Nullable<int> BikeQty { get; set; }
        public string BikeDesc { get; set; }
    }
}
